apiVersion: apps/v1
kind: Deployment
metadata:
  name: seminar-hall-app
  namespace: seminar-hall-booking
spec:
  replicas: 3
  selector:
    matchLabels:
      app: seminar-hall-app
  template:
    metadata:
      labels:
        app: seminar-hall-app
    spec:
      containers:
      - name: app
        image: ghcr.io/your-username/seminar-hall-booking:latest
        ports:
        - containerPort: 3000
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: seminar-hall-config
        - secretRef:
            name: seminar-hall-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/ready
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: seminar-hall-app-service
  namespace: seminar-hall-booking
spec:
  selector:
    app: seminar-hall-app
  ports:
  - name: frontend
    port: 3000
    targetPort: 3000
  - name: backend
    port: 5000
    targetPort: 5000
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: seminar-hall-app-hpa
  namespace: seminar-hall-booking
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: seminar-hall-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
